### PR TITLE
Updated executing with functional pipelines

### PR DESCRIPTION
**Pull request by Saiban0**
**functional not clean**
This pull request introduces several significant changes to improve error management and execution handling in the project. The changes include adding new error management functionalities, restructuring the execution flow, and updating various headers and source files to support these improvements.

### Error Management Enhancements:
* **New Error Management Header and Source Files**:
  * Added `error_management.h` to define error types and the `error_management` function.
  * Implemented `error_management.c` to handle different error scenarios and free resources appropriately.

### Execution Flow Improvements:
* **Refactoring Execution Functions**:
  * Updated `executing.h` to include new execution-related functions and the `t_pipex` structure.
  * Introduced `exec_init.c` to initialize the pipex structure and handle path extraction.
  * Added `exec_pipes.c` to manage pipe execution and child processes.
  * Modified `exec_simple.c` to switch between different execution paths and handle simple command execution.
  * Enhanced `exec_utils.c` with utility functions for closing pipes, waiting for execution, and creating forks.

### Build System Updates:
* **Makefile Adjustments**:
  * Updated `Makefile` to include new files for error management and execution handling.

### Miscellaneous:
* **Valgrind Configuration**:
  * Added a `.valgrindrc` file with options to keep debug info, check for leaks, and trace children processes.

These changes collectively enhance the robustness and maintainability of the codebase by improving error handling and streamlining the execution process.

### CODE REVIEW

**Comment by Saiban0** [comment]
Switched to draft PR to write some documentation

**Comment by blumbear** [comment]
👍

**Review by blumbear — COMMENTED** [review]
👍

**Review by blumbear — COMMENTED** [review]
👍

**Review by blumbear — APPROVED** [review]
👍

**Pull request merged**
